# Generated by Django 3.2.20 on 2023-08-31 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExchangeRate',
            new_name='Rate',
        ),
        migrations.RenameModel(
            old_name='ExchangeRateType',
            new_name='RateType',
        ),
    ]
