# Generated by Django 3.2.20 on 2023-09-01 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20230831_1635'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='rate',
            new_name='buy',
        ),
        migrations.AddField(
            model_name='rate',
            name='sell',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
