# Generated by Django 3.2.20 on 2023-09-05 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20230901_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='rate_date',
            field=models.DateField(default='2023-09-05'),
        ),
    ]
